name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Upload repo
      uses: actions/checkout@v3
      with: 
        path: solarspell
    - name: Upload repo to remote server
      env:
           SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
         ssh-agent -a $SSH_AUTH_SOCK > /dev/null
         ssh-add - <<< "${{ secrets.SSHKEY }}"
         scp -o StrictHostKeyChecking=no -r -P 22 solarspell root@161.35.106.238:/solarspell/
         cd /solarspell/
         docker-compose up -d
